Sogenactif bundle
ngdo-pro/WCS_Projet3 pull request #12
Opened 2017-01-12 19:48 UTC by ngdo-pro

Hi team,

Please, remember to : 

- composer install (new parameters are created, you will need to adapt them to your project)
- chmod 755 src/SogenatifBundle/Api/bin/* (request and response files from Sogenactif Api)
- change absolute paths in /src/Sogenactif/Api/params/pathfile to fit your project 
- app/console doctrine:migrations:migrate (you may need to reset your database)
- app/console doctrine:fixture:load

To test it : 
- Login as user
- Search 
- Select a baptism
- Confirm
- Click on a payment mean
- Enter a fake card number like 1234567812345600 ( it has to end with 00 to be a valid payment, 05 to fail )
- Return to website with api button (Retour à la boutique)

Autoresponse does work online, can't be tested offline

2017-01-13 07:59 UTC, wafaworks requested changes

2017-01-13 07:59 UTC, wafaworks commented on src/AppBundle/Repository/BaptismHasUserRepository.php
> +    /**
Sorry but the goal of this function doesn't appear very clear to me.. Could you be more precise on the commentary (maybe put an example?)

2017-01-13 07:59 UTC, wafaworks commented on src/AppBundle/Repository/BaptismHasUserRepository.php
> +    /**
And it appears that you did the "find out" mistake in many files, it's "this function find**s** out". But that's not a real problem, just to be meticulous.. ;)

2017-01-13 09:56 UTC, Kaji-U approved these changes
Good Job !

2017-01-13 10:28 UTC, shog189 commented on src/SogenactifBundle/Resources/config/doctrine/Transaction.orm.yml
> +        cardNumber:
About the entries relating to numbers, I do understand that it is a character chain but should it stay this way? Or couldn't it be a chain of INT?

2017-01-13 10:39 UTC, dbeauseigneur approved these changes
OK

2017-01-13 14:29 UTC, 2binfree approved these changes
ok

2017-01-14 09:12 UTC, wafaworks approved these changes
Now it's all good for me, thanks for the comment changes. 👍

2017-01-14 09:37 UTC, merged