Header footer integr
ngdo-pro/WCS_Projet3 pull request #16
Opened 2017-01-18 16:30 UTC by wafaworks

I've finished the header and footer, they are responsive.

2017-01-18 20:16 UTC, christianJCK commented on app/Resources/views/base.html.twig
> +        <link href="{{ asset('vendors/components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
I would have put bootstrap under the link of local files to upload them first, but otherwise good job Wafa! :)

2017-01-18 20:21 UTC, shog189 approved these changes

2017-01-18 20:21 UTC, christianJCK commented on app/Resources/views/base.html.twig
> +        <link href="{{ asset('vendors/components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
I would have put bootstrap under the link of local files to upload them first, but otherwise good job Wafa! :)

2017-01-18 21:36 UTC, Kaji-U approved these changes
Nice

2017-01-19 05:33 UTC, ngdo-pro requested changes
Nice work, some changes needs to be done :)

2017-01-19 05:33 UTC, ngdo-pro commented on app/Resources/views/base.html.twig
> +        <link href="{{ asset('vendors/components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
Actually, this line is not necessary, since it's already in vendor.css

2017-01-19 05:33 UTC, ngdo-pro commented on app/Resources/views/base.html.twig
> +      {# End #}
Can you completely remove the comment part ? :) Let's have no dead code :)

2017-01-19 05:33 UTC, ngdo-pro commented on app/Resources/views/base.html.twig
> +        <script src="{{ asset('vendors/components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
Same here, those two lines are unnecessary, already compiled in vendor.js

2017-01-19 05:33 UTC, ngdo-pro commented on app/Resources/views/modules/footer.html.twig
> +<footer class=" nav navbar-fixed-bottom footer">
can you remove the space before nav please ?

2017-01-19 05:33 UTC, ngdo-pro commented on app/Resources/views/modules/footer.html.twig
> +                <a class="footer-link" href="#">DEVENIR RESTAURATEUR</a>
Here and for the other texts, we need translations :) something like {{ 'placeholder' |trans({}, 'name_of_translation_file') }}

You can generate translations with `app/console translations:update --force --output-format=xlf fr`

2017-01-19 05:33 UTC, ngdo-pro commented on app/Resources/views/modules/header.html.twig
> +                    <li class="navbar-menu"><a class="navbar-link" href="">NOS RESTOS</a></li>
same here, we need traductions too :)

2017-01-19 05:33 UTC, ngdo-pro commented on app/Resources/views/modules/header.html.twig
> +                        <a class="dropdown-toggle text-uppercase" data-toggle="dropdown" aria-expanded="false" >
I believe we need a picture here, not sure if the functionality is ready, maybe add an issue ?

2017-01-19 05:33 UTC, ngdo-pro commented on src/BlogBundle/Resources/views/Default/index.html.twig
> +{% block body %}
careful, we are working with the 3-lvl templating, you can't extends base from a simple view, but i believe this is a placeholder, can you add it in comment ?

2017-01-19 05:33 UTC, ngdo-pro commented on web/dev/sass/views/_footer.sass
> +.hr--hidden
i think it should be like : 
.hr
  + &--hidden
     + display: none

2017-01-19 05:33 UTC, ngdo-pro commented on web/dev/sass/views/_footer.sass
> +  .footer-menu
same here

2017-01-19 05:33 UTC, ngdo-pro commented on web/dev/sass/views/_header.sass
> +  .navbar-nav
same here

2017-01-19 05:33 UTC, ngdo-pro commented on web/dev/sass/views/_header.sass
> +.navbar-default .navbar-toggle:focus, .navbar-default .navbar-toggle:hover
same here

2017-01-19 11:03 UTC, ngdo-pro approved these changes

2017-01-19 11:03 UTC, ngdo-pro commented
:+1:

2017-01-19 11:04 UTC, shog189 approved these changes
Good job Wafa !

2017-01-19 13:05 UTC, dbeauseigneur approved these changes
it's ok for me

2017-01-19 22:50 UTC, merged